### ISSUE TITLE
Visual tests failing

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-button#100]
![image](https://user-images.githubusercontent.com/6059356/42446698-e86c7836-837f-11e8-8c7c-efc436acaf0e.png)

**Comment by limonte** [comment]
Looks good now, closing.

**Comment by limonte** [comment]
Nope, still failing https://travis-ci.org/vaadin/vaadin-button/jobs/415327808

![image](https://user-images.githubusercontent.com/6059356/44020113-87a7d524-9ee9-11e8-8704-098efc806b55.png)

**Comment by web-padawan** [comment]
Note the same problem is happening also in https://github.com/vaadin/vaadin-text-field

**Comment by web-padawan** [comment]
Fixed by #109 and does not seem to happen anymore.
