### ISSUE TITLE
Make disabled primary button distinct from disabled secondary button (Lumo)

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-button#112]
Currently, a disabled primary button looks the same as a disabled secondary button.

![screen shot 2018-09-27 at 14 54 22](https://user-images.githubusercontent.com/66382/46144330-45015200-c265-11e8-8e73-9c8024bb0f49.png)

We should use `--lumo-primary-color-50pct` for the disabled primary button to make it stand out. We could also consider dropping the label opacity to make it more obvious that the button is disabled.

![screen shot 2018-09-27 at 14 55 46](https://user-images.githubusercontent.com/66382/46144381-70843c80-c265-11e8-897f-ec9f3a903417.png)

The `primary error` and `primary success` theme variants need to be handled separately as well.

**Comment by limonte** [comment]
Released in https://github.com/vaadin/vaadin-button/releases/tag/v2.1.2 🎉
