### ISSUE TITLE
Add `type` attribute to the API

### ISSUE THREAD

**Issue by sohrabtaee** [vaadin/vaadin-button#113]
It's not possible to use `vaadin-button` as submit or reset button in a form.

**Comment by tomivirkki** [comment]
This is probably not doable with a custom element (unless it extended the native `<input>` element). You'll need to add a click listener to the button and submit the form programmatically.

**Comment by sohrabtaee** [comment]
I tested it and it works.

```
const type = this.getAttribute('type');
this.shadowRoot.querySelector('button').setAttribute('type', type);
```

**Comment by tomivirkki** [comment]
Doesn't work here
http://jsfiddle.net/nmav4yoj/
