### ISSUE TITLE
Set cursor on all vaadin-button

### ISSUE THREAD

**Issue by KrifaYounes** [vaadin/vaadin-button#114]
vaadin-button = action 
so why there is no a cursor when mouse hover vaadin-button ? 
how to add a cursor on hover ?

**Comment by jouni** [comment]
Please follow [the corresponding issue](https://github.com/vaadin/vaadin-lumo-styles/issues/37) in Lumo styles repository.

As a workaround, add the following:

```html
<dom-module id="cursor-for-buttons" theme-for="vaadin-button">
  <template>
    <style>
      :host {
        cursor: pointer;
      }
    </style>
  </template>
</dom-module>
```
