### ISSUE TITLE
Disabled button with theme primary success doesn't look disabled

### ISSUE THREAD

**Issue by imneeazmi** [vaadin/vaadin-button#115]
### Description
When button with theme _primary success_ is _setEnabled(false)_, doesn't look disabled.

`<vaadin-button class="test-button" disabled="" role="button" theme="primary success" aria-disabled="true"><iron-icon icon="vaadin:plus" disabled=""></iron-icon><span>Disabled Button</span></vaadin-button>`

Looks like this:
![disabled success button](https://user-images.githubusercontent.com/22928748/48251912-2da9ad00-e43e-11e8-8eaa-516bdbde0be7.PNG)

But previous Valo theme (tested from [here](https://cdn.vaadin.com/vaadin-valo-theme/2.0.0-alpha5/demo/buttons.html) with inspect element change setting to add disabled) looks like this:
![primary_success_disabled_valo](https://user-images.githubusercontent.com/22928748/48251943-41edaa00-e43e-11e8-9f92-18d7aa05250d.PNG)

`<vaadin-button theme="success primary" role="button" disabled="" aria-disabled="true">Primary</vaadin-button>`

### Expected Result
Button should at least look disabled.

**Comment by web-padawan** [comment]
Thanks for the issue. The incorrectly applied styles taking precedence are here:

https://github.com/vaadin/vaadin-button/blob/181efe47ce9cfd02429c8df4fe3649d7655f2a79/theme/lumo/vaadin-button-styles.html#L193

So, the workaround used here does not override it:
https://github.com/vaadin/vaadin-button/blob/181efe47ce9cfd02429c8df4fe3649d7655f2a79/theme/lumo/vaadin-button-styles.html#L53

@jouni should we add `:not([disabled])` for all the themes? 
Also, looks like we now need to add proper visual tests for all the themes.

**Comment by limonte** [comment]
Released in https://github.com/vaadin/vaadin-button/releases/tag/v2.1.2 🎉
