### ISSUE TITLE
Click event is fired for disabled button

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-button#116]
Expectation:
It's impossible to click on a disabled button. Even via javascript. This is how native button works

Reality:
`disabledVaadinButton.click();` fires a click event.

Can be reproduced in Vaadin demos:
<img width="707" alt="screenshot 2018-11-26 at 10 48 15" src="https://user-images.githubusercontent.com/28781210/49002761-220df400-f169-11e8-9665-f033b020e08a.png">

**Comment by web-padawan** [comment]
Confirmed that the native `<button>` works as expected, so `vaadin-button` should work the same.
