### ISSUE TITLE
[material] Slotted icon not positioned correctly 

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-button#118]
_From @masbaehr on December 13, 2018 15:55_

```java

		Button btn = new Button("Go!", new Icon(VaadinIcon.AUTOMATION));
		btn.addClickListener(listener -> {
			Notification notification = new Notification(getTranslation("Not yet implemented"), 3000, Position.MIDDLE);
			notification.open();
		});
```
Renders:
![image](https://user-images.githubusercontent.com/38694044/49950046-59192f00-fef7-11e8-9c25-158142dcf929.png)

Expected:
![image](https://user-images.githubusercontent.com/38694044/49950062-633b2d80-fef7-11e8-83c1-12d87821bbc4.png)

(Should be aligned like it is with Lumo Theme)
Especially since the API setIconAfterText should work as it does with Lumo

Probably this can be easily fixed by changing this CSS:
![image](https://user-images.githubusercontent.com/38694044/49950285-d0e75980-fef7-11e8-9ff5-2b3ce2cb955e.png)

_Copied from original issue: vaadin/vaadin-material-styles#81_

**Comment by web-padawan** [comment]
@jouni the style has been implemented in vaadin/vaadin-material-styles@a46e0af2207b058e431e46d8c50bdc0cd8660001

In Lumo we do have `display: inline-block`:

https://github.com/vaadin/vaadin-button/blob/564762a0ad91b8b4beae402796a8c0555c2f4c6c/theme/lumo/vaadin-button-styles.html#L219

In Material we have `display: block`:
https://github.com/vaadin/vaadin-button/blob/564762a0ad91b8b4beae402796a8c0555c2f4c6c/theme/material/vaadin-button-styles.html#L127

Should we align it, or is there any reason for Material to look differently?

**Comment by masbaehr** [comment]
https://material.io/design/components/buttons.html
I suggest to stick with the usually expected way of showing a button

![image](https://user-images.githubusercontent.com/38694044/50290956-81f87180-046d-11e9-91e1-92415a0aeb4a.png)

**Comment by jouni** [comment]
The problem is actually in `vaadin-button-flow`, which does not use the `prefix` and `suffix` slots for icons.

That said, it would probably make sense to support icons in the main slot as well, like Lumo does.

I have a faint recollection that `display: block` avoids some baseline alignment issues.

**Comment by web-padawan** [comment]
The actual issue described in the above comment should be fixed by https://github.com/vaadin/vaadin-button-flow/pull/133
