### ISSUE TITLE
Performance problem in rendering

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-button#128]
Creating a button with any text causes style recalculations during rendering. This leads to https://github.com/vaadin/flow/issues/5447

<img width="914" alt="Screenshot 2019-04-10 at 9 37 07" src="https://user-images.githubusercontent.com/260340/55857558-1b12db80-5b76-11e9-88c1-ba0276063281.png">

**Comment by web-padawan** [comment]
Already agreed on reverting #122 and #125 to fix that (it would also fix #127)

**Comment by web-padawan** [comment]
Note, the true reason is using `innerText` but I still think we need to revert because of #127.

**Comment by web-padawan** [comment]
Closing as the code introducing this has been reverted and fix released in 2.1.5
