### ISSUE TITLE
Convert to Polymer 3

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-button#131]

**Comment by abdonrd** [comment]
There are news here?

**Comment by web-padawan** [comment]
Not really. This component is planned to be done as part of the bigger batch targeting Vaadin 18 (to be release in December). Those are our preliminary plans, nothing is set in stone yet.

Converting the component itself is a small effort but we need to figure out if the suggested fixes  for a11y issues, namely #96 and #144 are working properly. Also we might want to look at #73

**Comment by abdonrd** [comment]
Ok, thanks @web-padawan! We are starting a new project with LitElement and we wanted to use the Vaadin Button component, but not if we have to rely on Polymer Library.

**Comment by web-padawan** [comment]
Update: we are going to convert to Polymer 3 first, and update tests. This should make further conversion easier.
