### ISSUE TITLE
add polymer to dev dependencies

### ISSUE THREAD

**Issue by WanielDeiss** [vaadin/vaadin-button#140]
i don't want to install polymer globally, i prefer it to install it to the dev dependencies. then i don't need to switch my global polymer version, if i go into another (older/newer) project

if you like this idea, pull-request is incomming ;)

**Comment by web-padawan** [comment]
Thanks for the issue. While it might be convenient for someone, please keep in mind that every `polymer-cli` installation brings a lot of dependencies including `puppeteer` which is huge.

Polymer CLI is still installed in Travis, but that should be handled by the build cache.

>  i don't need to switch my global polymer version

Please note that Polymer CLI is in maintenance mode and not actively updated anymore.
We don't usually switch version of it (as we do not have any Polymer 1 projects).

In the next generation we will switch to `es-dev-server` which is a modern alternative.
But for Polymer-based components we are not inclined to change the dev dependencies.

So let me close this issue.
