### ISSUE TITLE
Refactor vaadin-button styles towards reusability, maybe -> vaadin-lumo-styles?

### ISSUE THREAD

**Issue by lkraav** [vaadin/vaadin-button#142]
Background: https://github.com/vaadin/vaadin-button/issues/79 and https://github.com/vaadin/vaadin-lumo-styles/issues/5

## Problem

Many website designs suggest button style navigation elements for UX reasons. `vaadin-button` seems like the handy choice, but it's not valid HTML5 to nest `<button>` element inside `<a>` - transparent elements can have no interactive descendants: https://stackoverflow.com/questions/6393827/can-i-nest-a-button-element-inside-an-a-using-html5

Vice versa is also blocked, see https://validator.w3.org/#validate_by_input

```
<!DOCTYPE html>
<html lang>
<head>
  <title>button vs a</title>
</head>
<a href="/"><button>Hello world</button></a>
<button><a href="/">Hello world</a></button>
</html>
```

Error: The element button must not appear as a descendant of the a element.
From line 6, column 13; to line 6, column 20
` href="/"><button>Hello `

Error: The element a must not appear as a descendant of the button element.
From line 7, column 9; to line 7, column 20
`>↩<button><a href="/">Hello `

It is highly likely not profitable for SEO to do `vaadin-button onclick=window.location.href` :heavy_plus_sign: there's probably other undesired side-effects.

Since we're blocked in both element nesting directions within the currently available toolbelt, I'm feeling like `vaadin-button` styling should maybe be a re-usable mixin, so that it'd also be possible to style native `<a>` elements as buttons?

Your thoughts? cc @jouni @web-padawan

**Comment by web-padawan** [comment]
Sorry about leaving this issue without an answer. Let me close it in favor of vaadin/vaadin-lumo-styles#5 and continue there.
