### ISSUE TITLE
Button should not get focus-ring on tap/click

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-button#32]
Currently, button which contains DOM nodes gets focus-ring after click.

Reproducible in the 2nd example https://cdn.vaadin.com/vaadin-button/1.0.0/demo/

**Comment by YuriyVaadin** [comment]
It seems that it is not a problem with focus-ring. It is about styles for focused state. 
![vaadin-button](https://user-images.githubusercontent.com/29372419/27946014-70579644-62f8-11e7-883a-fff9849b8f50.png)

**Comment by jouni** [comment]
Can’t reproduce on my iPhone 6S, iOS 10.3.2.

On the other hand, that button (the 2nd example) doesn’t give me any visual feedback that I’m clicking the image, and I’m wondering if anything is happening. The other buttons at least give the `-webkit-tap-highlight-color` flash.

**Comment by jouni** [comment]
Can reproduce on macOS Safari, though. The focus handling is a bit different than for a native button element. I suppose the host element gets the focus in vaadin-button when you click it?

**Comment by tomivirkki** [comment]
Works with the latest version. Closing.
