### ISSUE TITLE
Remove listeners on disconnectedCallback()

### ISSUE THREAD

**Issue by abdonrd** [vaadin/vaadin-button#38]
Polymer docs reference: [Add and remove listeners imperatively](https://www.polymer-project.org/2.0/docs/devguide/events#imperative-listeners).

**Comment by tomivirkki** [comment]
The element only adds listeners to itself. As the linked document states: "An element adding an event listener to itself or one of its shadow DOM children shouldn't prevent the element from being garbage collected", it shouldn't be necessary to remove them on disconnect, right? Or is this different for Gesture events?

**Comment by abdonrd** [comment]
Oh, rigth! I guess I read wrong. Thank you @tomivirkki!
