### ISSUE TITLE
Improve default theme/styles

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-button#41]
The current default styles, while being platform native, do not give a great dev experience, when trying to do simple customizations.

For example, you can’t change the colors of a `vaadin-button` like this:

```css
vaadin-button {
  background-color: blue;
  color: white;
}
```

That just ends up styling the host element (as it should) while the internal native button is shown above it. There are plenty of other visual properties a developer might want to quickly tweak, such as font and border styles, but they don’t end up affecting the visuals as expected.

The default height of the button is also narrower on iOS than for a native button element.

**Comment by manolo** [comment]
IMO we should provide also some default styling so the button looks the same in all platforms, and aligned with other elements like vaadin-text-field. Obviously it needs to be neutral and give the option to the user to easily removing styling to show the default platform button.
Things I see misaligned with text-box are height and border (line, focus, radius)

**Comment by jouni** [comment]
This is pretty much the same issue as https://github.com/vaadin/vaadin-checkbox/issues/39

Changing the default to Valo, as we are currently planning, would solve these issues.

**Comment by manolo** [comment]
wdyt about having some quick mechanism to quick switch to native for instance `theme=natve` or just `native` so as the user has not to write a theme overriding valo ?

**Comment by jouni** [comment]
The idea is that you could still import the element without a theme (i.e. `vaadin-button-notheme.html`), so you get something like the current default theme as the starting point. No extra API needed.

**Comment by jouni** [comment]
And since the current styling/theming mechanism is global, and you can’t just target a single instance with a style module, having instance based API is not a good idea.

**Comment by tomivirkki** [comment]
Lumo delivered as the default theme nowadays. `src/vaadin-button.html` can be imported for an unstyled button. Closing.
