### ISSUE TITLE
[2.0.0-alpha1] Demo and Docs point to 1.0.4

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-button#54]
Was hoping to check out the 2.0 demo and docs, but the links on the Releases page point to 1.0.4.

**Comment by web-padawan** [comment]
Thank you for reporting this issue! The links were updated so the [demo](https://cdn.vaadin.com/vaadin-button/2.0.0-alpha1/demo/#button-basic-demos) and [API docs](https://cdn.vaadin.com/vaadin-button/2.0.0-alpha1/#/elements/vaadin-button) are now available. We still work on the Valo theme improvements and there has been a bunch of changes recently, so there are some tags lacking proper release docs links, those should be updated soon.
