### ISSUE TITLE
Button appears broken on IE11 when serving a bundled app

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-button#66]
Button looks fine when running in development mode, but after building with `polymer build` and serving the result, button (with default Lumo style) appears as follows:
![screenshot 2018-02-08 13 29 48](https://user-images.githubusercontent.com/1222264/35970831-73d7ae54-0cd4-11e8-8706-f6c4c12600c9.png)

**Comment by jouni** [comment]
Not really sure. First suspicion is that it could be cause by the same thing as #63

**Comment by web-padawan** [comment]
@jouni This is actually caused by HTML minification. The problem appears once you remove the whitespace between `<div part="label">` and the `<slot>` inside it.

**Comment by jouni** [comment]
Right, that makes sense. Here’s the styles that cause it to break then: https://github.com/vaadin/vaadin-button/blob/master/src/vaadin-button.html#L61-L68

**Comment by web-padawan** [comment]
@jouni should we move those styles to the theme and only apply them to the `icon` button? Having those in the core styles looks a bit weird and not currently covered with any test.
