### ISSUE TITLE
Button with "tertiary-inline" theme variation has unexpected padding

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-button#67]
The demo says that button with `theme="tertiary-inline"` should be usable as part of a regular text content, and in the inline formatting context vertical padding are not expected to work, but here we still have those:

![screen shot 2018-02-22 at 11 48 53](https://user-images.githubusercontent.com/10589913/36531476-b4536f7a-17c6-11e8-9464-537ddfb6a4eb.png)

Personally I faced this issue when trying to use this theme variation in the expense-manager.

@jouni WDYT? should this be fixed or considered working as intended?

**Comment by jouni** [comment]
Hmm. I suppose it’s not expected, although currently intended (or then I’ve forgotten to reset those after some refactoring) 😄 

The only reason to keep the padding is to have a larger click target. Okay to me to remove those.
