### ISSUE TITLE
Styling buttons as links

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-button#79]
This is the complementary of https://github.com/vaadin/vaadin-lumo-styles/issues/5 i.e. support for a `vaadin-button` to appear as a simple link (`a`). The `tertiary` theme looks like a link, but it occupies additional space.

**Comment by heruan** [comment]
Oops, I missed that! Yes, it seems to fit exactly what I meant!

**Comment by web-padawan** [comment]
It used to take some undesired space, actually. This has been fixed in #68. Glad this helped!

**Comment by heruan** [comment]
Working on https://github.com/vaadin/vaadin-text-field/pull/213 I tried to use a `tertiary-inline` button instead of a link, but I see it hides the label overflow while a link does not; see https://jsfiddle.net/heruan/h5aksL36/ for example.

<img width="219" alt="screen shot 2018-03-31 at 08 37 36" src="https://user-images.githubusercontent.com/851745/38160480-295f05bc-34bf-11e8-9169-09e227de4ea3.png">

Would it be acceptable to set `overflow: visible` on the label part for the `tertiary-inline` theme?
